development: &default
  adapter: postgresql
  encoding: unicode
  database: bar-manager-development
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: bar-manager-test